---
- name: Configurar servidor de aplicação Java
  hosts: app01

  user: vagrant
  become: yes

  vars:
    - dbhost: "db01"
    - dbname: "notes"
    - dbusername: "notesapps"
    - dbpassword: "devopsmãonamassa"
  tasks:
    - name: Configurar hosts do lab ansible
      lineinfile:
        dest: /etc/hosts
        state: present
        line: "{{item}}"
      with_items:
        - 192.168.1.2 control-node
        - 192.168.1.3 app01
        - 192.168.1.4 db01

    - name: Adicionar usuario de app
      user:
        name: app
        comment: Usuario de aplicação
        uid: 500

    - name: Instalação do Maven
      yum:
        name: maven
        state: latest

    - name: Instalação do Java
      yum:
        name: java-1.8.0-openjdk
        state: latest

    - name: Criação do diretorio de app
      file:
        path: /opt/notes
        state: directory
        owner: app
        group: app

    - name: Clone repositorio git Notes - app
      git:
        repo: "https://github.com/callicoder/spring-boot-mysql-rest-api-tutorial.git"
        dest: /opt/notes
        clone: yes
        force: yes

    - name: Configurar arquivo de propriedades para camada de banco de dados
      template:
        src: application.properties
        dest: /opt/notes/src/main/resources/application.properties

    - name: Gerar pacote da aplicação
        command: mvn -f /opt/notes.pom.xml package
        become_user: app 
